site_name: Your Docs
site_url: https://<YOUR_GH_USERNAME>.github.io/<YOUR_REPO>/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Guides:
      - Getting Started: getting-started.md
      - Install: install.md
      - Review Workflow: review-workflow.md
  - Downloads: downloads.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - search
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
      # Generate a PDF per page (default)
      # combined: false

      # OR generate a single combined PDF:
      # combined: true
      # combined_output_path: pdf/combined.pdf

